Allow copying multiple files to OEMDRV

diff --git a/kvmboot b/kvmboot
--- a/kvmboot
+++ b/kvmboot
@@ -77,7 +77,7 @@ opt_no_cloud_init=0
 opt_no_reboot=0
 opt_emit_ansible_creds=0
 opt_print_xml=0
-opt_oemdrv=
+opt_oemdrv=()
 # Collect optional arguments
 while [ -n "$1" ] ; do
     arg="$1"
@@ -143,7 +143,7 @@ while [ -n "$1" ] ; do
       ;;
     --oemdrv)
       shift
-      opt_oemdrv="$1"
+      opt_oemdrv+="$1"
       ;;
     --disk)
       shift
@@ -700,13 +700,15 @@ if [ -n "$opt_oemdrv" ]; then
     fatal 1 "Could not allocate space in partition file: ${partitionfile}"
   fi
 
-  if ! mkfs.fat -F32 -S 512 "$partitionfile" >/dev/null; then
+  if ! mkfs.fat -n "OEMDRV" -F32 -S 512 "$partitionfile" >/dev/null; then
     fatal 1 "Could not FAT32 filesystem in partition file: ${partitionfile}"
   fi
 
-  if ! mcopy -i "${partitionfile}" "$opt_oemdrv" "::$(basename "$opt_oemdrv")"; then
-    fatal 1 "Failed copy $opt_oemdrv to $partitionfile as $(basename "$opt_oemdrv")"
-  fi
+  for fname in "${opt_oemdrv[@]}"; do
+    if ! mcopy -i "${partitionfile}" "$fname" "::$(basename "$fname")"; then
+      fatal 1 "Failed copy $fname to $partitionfile as $(basename "$fname")"
+    fi
+  done
 
   # Get the OEM drive file
   oemdrv_img="$(mktemp)"
